### ISSUE TITLE
Filter OTU table based on a specific treatment

### ISSUE THREAD

**Issue by Madegwa** [schuyler-smith/phylosmith#13] opened 2021-01-25 11:36 UTC
Hello thanks once more for the awesome package, its really helping me with my thesis. 
I have a question on filtering of the OTU table in Phylosmith
I have sequenced data for 4 weeks (i sampled soils once each week), i want to filter the OTU table for each week, so that i can compare how the OTU numbers are changing each week. 
Is it possible to do that in the Pylosmith package?
Any assistance will be highly appreciates. 
Yvonne

**Comment by schuyler-smith** [comment] 2021-01-29 15:21
Hi Yvonne, I think you want to use the taxa_filter() function, the arguments for 'treatment' would be week and then provide the argument 'subset' and assign it which week you specifically want to look at. Please let me know if this doesn't work as intended, or if that is not what you were looking for!

**Comment by Madegwa** [comment] 2021-01-30 10:07
Hi Schuyler-smith
Thank you very much, that is exactly what i was looking for!
Thanks again
Yvonne

**Closed** 2021-01-30 10:07 UTC
